name: Flake check

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SECRETS_DEPLOY_KEY }}

      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix flake check --no-build --show-trace
